apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: neo4j-operator
  template:
    metadata:
      labels:
        name: neo4j-operator
    spec:
      serviceAccountName: neo4j-operator
      containers:
        - name: neo4j-operator
          # Replace this with the built image name
          image: lantonia/neo4j-operator:latest
          command:
          - neo4j-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "neo4j-operator"
